name: Bump dappnode upstream version

on:
  schedule:
    - cron: "00 */4 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx @dappnode/dappnodesdk github-action bump-upstream
        env:
          GITHUB_TOKEN: ${{ secrets.DAPPNODE_GITHUB_READ_TOKEN }}
